apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bbr3mb1xc-go 
  janus-idp.io/tekton: bbr3mb1xc-go
  backstage.io/kubernetes-id: bbr3mb1xc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bbr3mb1xc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml